name: chats_ton
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.2.8
  provider: ^6.0.5
  # device_preview: ^1.1.0
  flutter_svg: ^2.0.7
  # device_info_plus: ^9.1.0
  country_code_picker: ^3.0.0
  shared_preferences: ^2.2.2
  get: ^4.6.6
  image_picker: ^1.0.4
  google_fonts: ^6.1.0
  # readsms: ^0.0.2+2
  cached_network_image: ^3.3.0
  # flutter_contacts: ^1.1.7+1
  status_view: ^0.0.2
  flutter_story_view: ^0.0.3
  # just_audio_cache: ^0.1.2
  # just_audio: ^0.9.35
  # just_audio: ^0.9.35
  # audio_session: ^0.1.16
  video_player: ^2.7.2
  # flick_video_player: ^0.5.0
  # video_player_media_kit: ^1.0.4
  # media_kit_libs_android_video: any
  # media_kit_libs_ios_video: any
  # media_kit_libs_macos_video: any
  flutter_cache_manager: ^3.3.1
  flutter_callkit_incoming: ^2.0.0+2
  # localstore: ^1.3.5
  timeago: ^3.5.0
  # social_media_audio_recorder: ^0.0.8
  # audio_waveforms: ^1.0.4
  fast_contacts: ^3.0.3
  permission_handler: ^11.0.1
  fast_cached_network_image: ^1.2.0
  # zego_uikit_prebuilt_call: ^3.17.1
  # zego_uikit_signaling_plugin: ^2.6.1
  # mime: ^1.0.4
  # video_thumbnail: ^0.5.3
  # agora_token_service: ^0.1.2
  firebase_messaging: ^14.7.2
  stream_video_push_notification: ^0.1.1
  stream_chat_flutter: ^6.11.0
  # stream_chat_flutter_core: ^6.10.0
  stream_video_flutter: ^0.1.1
  stream_chat_persistence: ^6.9.0
  dart_jwt_token: ^0.0.3
  flutter_local_notifications: ^16.1.0
  # videosdk: ^1.1.6
  # flutter_firebase_chat_core: ^1.6.7
  # flutter_chat_types: ^3.6.2



  # voice_message_package:
  #   git: https://github.com/AhsinMehmood/voice_message_player.git
  flutter_vibrate: ^1.3.0
  font_awesome_flutter: ^10.6.0
  path_provider: ^2.1.1
  collection: ^1.17.2
  desktop_drop: ^0.4.4
  uni_links: ^0.5.1
  photo_manager: ^2.7.2
  # agora_rtc_engine: ^6.2.4
  # record: ^4.4.4
  # rxdart: ^0.27.7
  # flutter_vlc_player: ^7.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
