// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC75Dp_i3I63s0GpeuGVrv4ahh1UTKmKcI',
    appId: '1:359885495778:web:fd72107ddfd28c1ff92dbb',
    messagingSenderId: '359885495778',
    projectId: 'mpl11-92ebf',
    authDomain: 'mpl11-92ebf.firebaseapp.com',
    databaseURL: 'https://mpl11-92ebf.firebaseio.com',
    storageBucket: 'mpl11-92ebf.appspot.com',
    measurementId: 'G-YJQYVFG9WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsi19143wtD9sbKlVzJ6NLyORxYOPFxps',
    appId: '1:359885495778:android:92bced6567a8c4f8f92dbb',
    messagingSenderId: '359885495778',
    projectId: 'mpl11-92ebf',
    databaseURL: 'https://mpl11-92ebf.firebaseio.com',
    storageBucket: 'mpl11-92ebf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbBmQwGK-r28K8A1YcG0rnpDtOiAPn5Zk',
    appId: '1:359885495778:ios:5e0032e78699bb68f92dbb',
    messagingSenderId: '359885495778',
    projectId: 'mpl11-92ebf',
    databaseURL: 'https://mpl11-92ebf.firebaseio.com',
    storageBucket: 'mpl11-92ebf.appspot.com',
    androidClientId: '359885495778-13mdn45mop2mc3udr90m96nmim6nl0ml.apps.googleusercontent.com',
    iosClientId: '359885495778-jdj8r3s3acfg1tgdae05fjjcqlbo7fi3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatsTon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbBmQwGK-r28K8A1YcG0rnpDtOiAPn5Zk',
    appId: '1:359885495778:ios:22276e2e6c1fa47df92dbb',
    messagingSenderId: '359885495778',
    projectId: 'mpl11-92ebf',
    databaseURL: 'https://mpl11-92ebf.firebaseio.com',
    storageBucket: 'mpl11-92ebf.appspot.com',
    androidClientId: '359885495778-13mdn45mop2mc3udr90m96nmim6nl0ml.apps.googleusercontent.com',
    iosClientId: '359885495778-0s2rtivao8bcjgtfgbjl5ep71k29fr5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatsTon.RunnerTests',
  );
}
