// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCHGlT8JNGAnySk3NC9KLjcAoNjlmpExQ',
    appId: '1:916351585483:web:2293ed57f179461ad39f4e',
    messagingSenderId: '916351585483',
    projectId: 'chats-ton',
    authDomain: 'chats-ton.firebaseapp.com',
    storageBucket: 'chats-ton.appspot.com',
    measurementId: 'G-3H0XXZJZKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmRHqWuQ3lUA0aWURtdxPRB0X9F9Q01ZE',
    appId: '1:916351585483:android:4c7947d55aa7d866d39f4e',
    messagingSenderId: '916351585483',
    projectId: 'chats-ton',
    storageBucket: 'chats-ton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkVbXzJb1rez3U0awKT7Kws7bm04FKOLc',
    appId: '1:916351585483:ios:72306fc86deb12c4d39f4e',
    messagingSenderId: '916351585483',
    projectId: 'chats-ton',
    storageBucket: 'chats-ton.appspot.com',
    iosBundleId: 'com.example.chatsTon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkVbXzJb1rez3U0awKT7Kws7bm04FKOLc',
    appId: '1:916351585483:ios:4967d6eeb7717980d39f4e',
    messagingSenderId: '916351585483',
    projectId: 'chats-ton',
    storageBucket: 'chats-ton.appspot.com',
    iosBundleId: 'com.example.chatsTon.RunnerTests',
  );
}
